# Generated by Django 5.2 on 2025-05-06 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_store_user_storeuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importreceipt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='user',
        ),
        migrations.AddField(
            model_name='importreceipt',
            name='store_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.storeuser'),
        ),
        migrations.AddField(
            model_name='order',
            name='store_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.storeuser'),
        ),
        migrations.AddField(
            model_name='product',
            name='store_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.storeuser'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='store_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.storeuser'),
        ),
    ]
