# Generated by Django 5.2 on 2025-05-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_importreceipt_user_remove_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='store',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='store_user',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProductInventory',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
